kind: Service
apiVersion: v1
metadata:
  name: azuredevops
  labels:
    app: azuredevops
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31200
  selector:
    app: azuredevops
  type: LoadBalancer
